### ISSUE TITLE
Support for ndarray 0.13.0

### ISSUE THREAD

**Issue by PierreHenry63** [oracleofnj/einsum#11]
Hello,

Many thanks for the work on the crate, I was wondering if it would be possible to add support for ndarray 0.13.0 ?

Best regards,
Pierr

**Comment by oracleofnj** [comment]
I just published version 0.5.0 of my crate which supports 0.13.0. Please give it a try!

**Comment by PierreHenry63** [comment]
this is working great, thanks a lot!
